Type: Jupyter Notebook Extension
Name: Nbextensions edit menu item
Description: Add an edit-menu item to open the nbextensions configurator page
Main: main.js
Compatibility: 4.x, 5.x
Icon: icon.png
tags:
- configurator
- menu
